@startuml


class Main {
  void 勤怠管理(String[] args)
  boolean is勤怠入力(){return args[0].equals("input")}
  boolean is集計(){return args[0].equals("total")}
}

package ユーザーインタフェース層 <<勤怠更新パッケージ>> {
 Main --> 勤怠入力API
 勤怠入力API -->  勤怠入力リクエスト
 勤怠入力リクエスト -->  勤怠日リクエスト
 勤怠入力リクエスト -->  開始時間リクエスト
 勤怠入力リクエスト -->  終了時間リクエスト

class 勤怠入力API {
  void 勤怠入力(勤怠入力リクエスト)
 }

class 勤怠入力リクエスト {
  -private KintaiDayForm kintaiDayForm
  -private KaishiZikanForm kaishiZikanForm
  -private SyuryoZikanForm syuryoZikanForm
  +勤怠日毎データ create()
 }

class 勤怠日リクエスト {
  -private String value
  KintaiDay getValueObject()
 }

class 開始時間リクエスト{
  -private String value
  KaishiZikan getValueObject()
 }

class 終了時間リクエスト {
  -private String value
  SyuryoZikan getValueObject()
 }

}


package アプリケーション層 <<勤怠更新パッケージ>> {
勤怠入力API --> 勤怠入力サービス
class 勤怠入力サービス {
  -勤怠IDレポジトリー
  -勤怠レポジトリー
  void 登録(勤怠日毎データ){ }

 }

}

package ドメイン層 <<勤怠更新パッケージ>> {
  勤怠日毎データ *-- 勤務日付
  勤怠日毎データ *-- 開始時間
  勤怠日毎データ *-- 終了時間
  勤怠入力リクエスト -->  勤怠日毎データ
  勤怠入力サービス --> 勤怠日毎データエンティティファクトリー
  勤怠日毎データエンティティファクトリー --> 勤怠ID
  勤怠日毎データエンティティファクトリー --> 勤怠日毎データ
  勤怠日毎データエンティティファクトリー --> 勤怠日毎データエンティティ
  勤怠入力サービス --> 勤怠レポジトリー
  勤怠日毎データエンティティ --> 勤怠ID
  勤怠日毎データエンティティ --> 勤務日付
  勤怠日毎データエンティティ --> 開始時間
  勤怠日毎データエンティティ --> 終了時間


class 勤怠日毎データエンティティファクトリー {
  +勤怠日毎データエンティティ create(勤怠ID,勤怠日毎データ)

}

class 勤怠日毎データ {
  -勤怠日付
  -開始時間
  -終了時間
}

class 勤怠日毎データエンティティ {
  -勤怠ID
  -勤怠日付
  -開始時間
  -終了時間
}

class 勤怠ID {
  -String
 }

class 勤務日付 {
  -String
 }

class 開始時間 {
  -String
 }

class 終了時間 {
  -String
 }

interface 勤怠レポジトリー{
勤怠レポジトリー : 勤怠ID create()
勤怠レポジトリー : void 登録(勤怠日毎データエンティティ)
勤怠レポジトリー : １ヶ月集計リスト 前月勤怠リスト検索()
}

}
note top
  一旦、前月の勤怠をリストを固定でとる設計とした
end note

package ユーザーインタフェース層_勤怠集計 <<勤怠集計パッケージ>> {
 Main --> 勤怠集計API

class 勤怠集計API #CCCCEE {
  １ヶ月集計view 勤怠集計()
 }
}

package アプリケーション層_勤怠集計 <<勤怠集計パッケージ>> {
勤怠集計API --> 勤怠集計サービス

class 勤怠集計サービス #CCCCEE {
  1ヶ月集計リスト 1ヶ月集計リスト参照()

 }
}
package ドメイン層_勤怠集計 <<勤怠集計パッケージ>> {
勤怠集計サービス -->  1ヶ月リスト
1ヶ月リスト -->  勤怠日毎データエンティティ
1ヶ月リスト -->  1ヶ月集計結果リスト
1ヶ月集計結果リスト -->  1ヶ月集計日毎データ

class 1ヶ月リスト #CCCCEE {
  -private List<勤怠日毎データエンティティ> list
  + List<1ヶ月集計結果リスト> 1ヶ月集計(勤怠日毎データエンティティ)
  - private filter休憩時間(勤怠日毎データエンティティ)
  - private 残業時間計算(勤怠日毎データエンティティ)
  - private 勤務時間計算(勤怠日毎データエンティティ)
 }

 class 1ヶ月集計結果リスト #CCCCEE {
   -private List<1ヶ月集計日毎データ> list
  }
 class 1ヶ月集計日毎データ #CCCCEE {
   -private 勤務日付 value
   -private 勤務時間 value
   -private 残業時間 value

  }
  note top
    勤務日付ごとの勤務時間と残業時間はわかるけど、
    勤務日付
    が被ったらとかどの社員のってのがわからないのが課題
  end note

}

@enduml